a = input('Digite algo: ')
print('É um número? ' , a.isnumeric())
print('É formado por letras? ' , a.isalpha())
print('É formado por letras e algarismos? ' , a.isalnum())
print('Há somente espaços? ' , a.isspace())
print('São letras maiúsculas? ' , a.isupper())
print('São letras minúsculas? ' , a.islower())
print('É um número decimal? ' , a.isdecimal())
print('É capitalizado? ' , a.istitle())
